components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 339978069723-ou36ab58leusercontent.com
            clientSecret: GOCSPX-p9Kly9b2
            scope:
              - email
              - profile
              - openid
#        accessTokenUri: https://www.googleapis.com/oauth2/v3/token
#        userAuthorizationUri: https://www.google.com/o/oauth2/auth
#        tokenName: oauth_token
#        authenticationScheme: query
#        clientAuthenticationScheme: form
#
#        resource:
#         userInfoUri: https://www.googleapis.com/userinfo/v2/me
#         preferTokenInfo: false