version: '3.3'
services:
  app:
    container_name: docker-my-spring
    image: spring-redis:v11
    build: .
    env_file:
      - .env
    ports:
      - "8090:8090"
    links:
      - redis
      - rabbitmq4

  redis:
    container_name: redis
    image: redis:latest
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"

  rabbitmq4:
    container_name: rabbitmq
    hostname: rabbitmq
    image: 'rabbitmq:3.10.5-management-alpine'
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

